# Generated by Django 3.2.6 on 2021-08-19 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='notice_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('content', models.CharField(max_length=4000)),
                ('writer', models.CharField(max_length=10)),
                ('write_dttm', models.DateTimeField()),
                ('good_cnt', models.IntegerField(default=0)),
            ],
        ),
    ]
